// Request Products
export const REQUEST_PRODUCTS_PENDING = "REQUEST_PRODUCTS_PENDING";
export const REQUEST_PRODUCTS_SUCCESS = "REQUEST_PRODUCTS_SUCCESS";
export const REQUEST_PRODUCTS_FAILED = "REQUEST_PRODUCTS_FAILED";

// Change Currency
export const SET_CURRENCY = "SET_CURRENCY";

// Manipulate Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_ITEM_COUNT = "INCREMENT_ITEM_COUNT";
export const DECREMENT_ITEM_COUNT = "DECREMENT_ITEM_COUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_ITEM_ATTRIBUTE = "SET_ITEM_ATTRIBUTE";

// Use Toasts
export const SHOW_TOAST = "SHOW_TOAST";
export const EXPIRE_TOAST = "EXPIRE_TOAST";